services:

  app:
    image: sonuku31/saitring-employee-manager:latest

    container_name: sonu-saitring-management

    ports:
      - "8080:8080"

    environment:

      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE}
      DB_MIN_IDLE: ${DB_MIN_IDLE}
      DB_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}
      DB_IDLE_TIMEOUT: ${DB_IDLE_TIMEOUT}
      DB_MAX_LIFETIME: ${DB_MAX_LIFETIME}
      DB_KEEPALIVE_TIME: ${DB_KEEPALIVE_TIME}
      DB_VALIDATION_TIMEOUT: ${DB_VALIDATION_TIMEOUT}

      # Frontend
      FRONTEND_URL: ${FRONTEND_URL}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # Brevo
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
      BREVO_OTP_TEMPLATE_ID: ${BREVO_OTP_TEMPLATE_ID}

      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}
      REDIS_CONNECT_TIMEOUT: ${REDIS_CONNECT_TIMEOUT}
      REDIS_TIMEOUT: ${REDIS_TIMEOUT}

      # Twilio
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}

      # Logging
      LOGGING_LOGSTASH_HOST: logstash:5000
      ENVIRONMENT: production

    depends_on:
      - logstash

    restart: unless-stopped


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.4

    container_name: sonu-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    restart: unless-stopped


  logstash:
    image: docker.elastic.co/logstash/logstash:9.5.4

    container_name: sonu-logstash

    ports:
      - "5000:5000"

    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

    depends_on:
      - elasticsearch

    restart: unless-stopped


  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.4

    container_name: sonu-kibana

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    ports:
      - "5601:5601"

    depends_on:
      - elasticsearch

    restart: unless-stopped


volumes:

  elasticsearch_data: